# This workflow builds a Maven project and publishes it to GitHub Packages
# when a pull request ke main dibuat atau release baru dibuat

name: Maven Package

on:
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # harus sama dengan id di <distributionManagement> di pom.xml
          settings-path: ${{ github.workspace }} # tempat untuk menyimpan settings.xml

      - name: Publish to GitHub Packages with Maven
        run: mvn deploy -Dsonar.skip=true -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # token default untuk akses GitHub Packages
